## td_Qobj usage example
Features of td_Qobj for the users.

In [1]:
from qutip import *
import time
import numpy as np

## Definition of time-dependant Qobj

td_Qobj are definied from list of Qobj:  
[Qobj0, [Qobj1, coeff1], [Qobj2, coeff2]]  
coeff can be one of: 
- function
- string
- np.array

In [2]:
# Definition of base Qobj and 
N = 4

def sin_w(t, args):
    return np.cos(args["w"]*t)

def cos_w(t, args):
    return np.cos(args["w"]*t)

tlist = np.linspace(0,10,10000)
tlistlog = np.logspace(-3,1,10000)


In [3]:
# constant td_Qobj
cte_td_Qobj = td_Qobj(destroy(N))
cte_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.          1.          0.          0.        ]
 [ 0.          0.          1.41421356  0.        ]
 [ 0.          0.          0.          1.73205081]
 [ 0.          0.          0.          0.        ]]

In [4]:
# td_Qobj with function based coeff
func_td_Qobj = td_Qobj([destroy(N),[qeye(N),cos_w]],args={"w":2})
func_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.41614684  1.          0.          0.        ]
 [ 0.         -0.41614684  1.41421356  0.        ]
 [ 0.          0.         -0.41614684  1.73205081]
 [ 0.          0.          0.         -0.41614684]]

In [5]:
# td_Qobj with sting based coeff
str_td_Qobj = td_Qobj([destroy(N),[qeye(N),"cos(w*t)"]],args={"w":2})
str_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.41614684  1.          0.          0.        ]
 [ 0.         -0.41614684  1.41421356  0.        ]
 [ 0.          0.         -0.41614684  1.73205081]
 [ 0.          0.          0.         -0.41614684]]

In [6]:
# td_Qobj with array based coeff
array_td_Qobj = td_Qobj([destroy(N),[qeye(N),np.cos(2*tlist)]],tlist=tlist)
array_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.41614684  1.          0.          0.        ]
 [ 0.         -0.41614684  1.41421356  0.        ]
 [ 0.          0.         -0.41614684  1.73205081]
 [ 0.          0.          0.         -0.41614684]]

In [7]:
# td_Qobj with array based coeff, log timescale
Log_array_td_Qobj = td_Qobj([destroy(N),[qeye(N),np.cos(2*tlistlog)]],tlist=tlistlog)
Log_array_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.41614684  1.          0.          0.        ]
 [ 0.         -0.41614684  1.41421356  0.        ]
 [ 0.          0.         -0.41614684  1.73205081]
 [ 0.          0.          0.         -0.41614684]]

In [8]:
# Reference
destroy(N) + qeye(N) * np.cos(2)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.41614684  1.          0.          0.        ]
 [ 0.         -0.41614684  1.41421356  0.        ]
 [ 0.          0.         -0.41614684  1.73205081]
 [ 0.          0.          0.         -0.41614684]]

## Mathematic
- addition (td_Qobj, Qobj)
- substraction (td_Qobj, Qobj)
- product (Qobj, scalar)
- division (scalar)

The examples are done with function type coefficients only, but work for any type of coefficient.  
Mixing coefficients type is possible, however this support would be removed if td_Qobj * td_Qobj is to be implemented.

In [9]:
# Build objects
o1 = td_Qobj([qeye(N),[destroy(N),sin_w]],args={"w":2})
o2 = td_Qobj([qeye(N),[create(N),cos_w]],args={"w":2})
t = np.random.random()*10

In [10]:
o3 = o1 + o2
print(o3(t) == o1(t) + o2(t))
o3 = o1 - o2
print(o3(t) == o1(t) - o2(t))
o3 = o1 + destroy(N)
print(o3(t) == o1(t) + destroy(N))
o3 = o1 - destroy(N)
print(o3(t) == o1(t) - destroy(N))

True
True
True
True


In [11]:
o3 = o1 * destroy(N)
print(o3(t) == o1(t) * destroy(N))
o3 = o1 * (0.5+0.5j)
print(o3(t) == o1(t) * (0.5+0.5j))
o3 = o1 / (0.5+0.5j)
print(o3(t) == o1(t) / (0.5+0.5j))

True
True
True


In [12]:
o1 = td_Qobj([qeye(N),[destroy(N),sin_w]],args={"w":2})
o2 = td_Qobj([qeye(N),[create(N),cos_w]],args={"w":2})
o1 += o2
print(o1(t) == (qeye(N)*2 + destroy(N)*sin_w(t,args={"w":2}) + create(N)*cos_w(t,args={"w":2})))

True


In [13]:
o1 = td_Qobj([qeye(N),[destroy(N),sin_w]],args={"w":2})
o2 = td_Qobj([qeye(N),[create(N),cos_w]],args={"w":2})
o1 -= o2
print(o1(t) == (destroy(N)*sin_w(t,args={"w":2}) - create(N)*cos_w(t,args={"w":2})))

o1 = td_Qobj([qeye(N),[destroy(N),sin_w]],args={"w":2})
o2 = td_Qobj([qeye(N),[create(N),cos_w]],args={"w":2})
o1 += -o2
print(o1(t) == (destroy(N)*sin_w(t,args={"w":2}) - create(N)*cos_w(t,args={"w":2})))

True
True


In [14]:
o1 = td_Qobj([qeye(N),[destroy(N),sin_w]],args={"w":2})
o1 *= destroy(N)
print(o1(t) == (destroy(N) + destroy(N)*destroy(N)*sin_w(t,args={"w":2})))

True


## Unitary operations: 
- conj
- dag 
- trans 
- norm: td_Qobj.dag * td_Qobj

In [15]:
o_real = td_Qobj([qeye(N),[destroy(N), sin_w]], args={"w":2})
o_cplx = td_Qobj([qeye(N),[create(N), cos_w]], args={"w":-1j})

print(o_real(t).trans() == o_real.trans()(t))
print(o_real(t).conj() == o_real.conj()(t))
print(o_real(t).dag() == o_real.dag()(t))

print(o_cplx(t).trans() == o_cplx.trans()(t))
print(o_cplx(t).conj() == o_cplx.conj()(t))
print(o_cplx(t).dag() == o_cplx.dag()(t))

True
True
True
True
True
True


In [16]:
# the operator norm correspond to c.dag * c. 
# Can only be used with td_qobj composed of one qobj.
td_cplx_f0 = td_qobj.td_Qobj([qeye(N)])
td_cplx_f1 = td_qobj.td_Qobj([[destroy(N)*create(N),sin_w]], args={'w':2.})
td_cplx_f2 = td_qobj.td_Qobj([[destroy(N),cos_w]], args={'w':2.})
td_cplx_f3 = td_qobj.td_Qobj([[create(N),1j*np.sin(tlist)]], tlist=tlist)

print(td_cplx_f0(t).dag()*td_cplx_f0(t) == td_cplx_f0.norm()(t))
print(td_cplx_f1(t).dag()*td_cplx_f1(t) == td_cplx_f1.norm()(t))
print(td_cplx_f2(t).dag()*td_cplx_f2(t) == td_cplx_f2.norm()(t))
print(td_cplx_f3(t).dag()*td_cplx_f3(t) == td_cplx_f3.norm()(t))

True
True
True
True


## Liouvillian and lindblad dissipator, to use in solver

Functions in qutip.superoperator can be used for tqQobj.

In [17]:
td_L = liouvillian(H=func_td_Qobj)
L = liouvillian(H=func_td_Qobj(t))
td_L(t) == L

True

In [18]:
td_cplx_f0 = td_qobj.td_Qobj([qeye(N)])
td_cplx_f1 = td_qobj.td_Qobj([[destroy(N)*create(N),sin_w]], args={'w':2.})

td_L = liouvillian(H=func_td_Qobj,c_ops=[td_cplx_f0,td_cplx_f1])
L = liouvillian(H=func_td_Qobj(t),c_ops=[td_cplx_f0(t),td_cplx_f1(t)])
print(td_L(t) == L)

True


In [19]:
td_P = spre(td_cplx_f1)
P = spre(td_cplx_f1(t))
print(td_P(t) == P)

True


## Getting the list back for the object

In [20]:
print(td_L.to_list())

[Quantum object: dims = [[[4], [4]], [[4], [4]]], shape = (16, 16), type = super, isherm = False
Qobj data =
[[ 0.+0.j          0.-1.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j        ]
 [ 0.+0.j          0.+0.j          0.-1.41421356j  0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j        ]
 [ 0.+0.j          0.+0.j          0.+0.j          0.-1.73205081j  0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j        ]
 [ 0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0.+0.j          0.+0.j          0.+0.j          0.+0.j
   0.+0.j          0

## Arguments modification

To change the args: td_qobj.arguments(new_args)

Call with other arguments without changing them: td_qobj.with_args(t, new_args)


In [21]:
def Args(t, args):
    return args['w']
td_args = td_qobj.td_Qobj([qeye(N), Args],args={'w':1.}) 
print(td_args(t) == qeye(N))
td_args.arguments({'w':2.})
print(td_args(t) == qeye(N)*2)
print(td_args.with_args(t,{'w':3.}) == qeye(N)*3)

True
True
True


When summing td_Qobj that have an arguments in common, each part keep their individual argument until the object's arguments is updated (method arguments).

In [22]:
td_args_1 = td_qobj.td_Qobj([qeye(N), [destroy(N), cos_w]],args={'w':1.})
td_args_2 = td_qobj.td_Qobj([qeye(N), [destroy(N), cos_w]],args={'w':2.})
td_str_sum = td_args_1 + td_args_2

# The sum operator remember the frequence of each part
print(td_str_sum(t) == 2*td_args_1(t)) 
print(td_str_sum(t) == td_args_1(t) + td_args_2(t)) 
# The sum operator remember the frequence of each part
print(td_str_sum.with_args(t, {'w':1}) == 2*td_args_1(t))# Updating the arguments affect each part.
td_str_sum.arguments({'w':1.})
print(td_str_sum(t) == 2*td_args_1(t))

False
True
True
True


## Other

In [23]:
# Obtain the sparce matrix at a time t instead of a Qobj
str_td_Qobj(1, data=True)

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 7 stored elements in Compressed Sparse Row format>

In [24]:
# Test is the td_Qobj does depend on time
print(cte_td_Qobj.const)
print(str_td_Qobj.const)

True
False


In [25]:
# Obtain the size, shape, oper flag etc:
# The td_Qobj.cte always exist and contain the constant part of the td_Qobj
# It can be used to get the shape, etc. since the td_Qobj do not directly have them.
td_cplx_f1 = td_qobj.td_Qobj([[destroy(N)*create(N),sin_w]], args={'w':2.})
print(td_cplx_f1.cte.dims)
print(td_cplx_f1.cte.shape)
print(td_cplx_f1.cte.isoper)
print(td_cplx_f1.cte)

[[4], [4]]
(4, 4)
True
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [26]:
# Creating a copy
str_td_Qobj_2 = str_td_Qobj.copy()
str_td_Qobj_2 += 1
str_td_Qobj_2(1) -  str_td_Qobj(1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]