#Basic Operations on Quantum Objects

###Contents
- [First Things First](#first)
- [The Qobj Class](#qobj)
- [Functions Acting on the Qobj Class](#functions)

<a id='first'></a>

## First Things First
<br>
<div class="warn">
**Warning**: Do not run QuTiP from the installation directory.
</div>

In order to load the QuTiP library we must first call the import statement:

In [13]:
from qutip import *

In addition, it is often necessary to load addition mathematical functions and plotting features from the NumPy and Matplotlib libraries, respectively:

In [15]:
import numpy as np
import pylab as plt

Here we have imported the Numpy package as "np" so that the functions included in this module can be called using the `np.func()` syntax.  In addition, the plotting functions from Pylab can be called via e.g. `plt.plot()`.

It is important to note that if we choose to import all of the functions directly from the modules using
```python
from numpy import *
from pylab import *
```
then the order in which we import QuTiP and these additional libraries is important.  In general, if using this import style, you must import QuTiP **last**:

```python
from numpy import *
from pylab import *
from qutip import *
```

<a id='qobj'></a>

##The Quantum Object Class

###Introduction
The key difference between classical and quantum mechanics lies in the use of operators instead of numbers as variables. Moreover, we need to specify state vectors and their properties. Therefore, in computing the dynamics of quantum systems we need a data structure that is capable of encapsulating the properties of a quantum operator and ket/bra vectors. The quantum object class, ``Qobj``, accomplishes this using a sparse matrix representation.

To begin, let us create a blank ``Qobj``:

In [16]:
Qobj()

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.]]

where we see the blank ``Qobj`` object with dimensions, shape, and data. Here the data corresponds to a 1x1-dimensional sparse matrix consisting of a single zero entry. 

<div class="info">
**Hint**: By convention, Class objects in Python such as ``Qobj()`` differ from functions in the use of a beginning capital letter.
</div>

We can create a ``Qobj`` with a user defined data set by passing a list or array of data into the ``Qobj``:

In [22]:
x = np.array([[1, 2, 3, 4, 5]])
Qobj(x)

Quantum object: dims = [[1], [5]], shape = [1, 5], type = bra
Qobj data =
[[ 1.  2.  3.  4.  5.]]

In [23]:
r = np.random.rand(4, 4)
Qobj(r)

Quantum object: dims = [[4], [4]], shape = [4, 4], type = oper, isherm = False
Qobj data =
[[ 0.60770407  0.12497888  0.9854267   0.86655998]
 [ 0.45037026  0.95719325  0.77046957  0.07683816]
 [ 0.07916973  0.7402108   0.74914042  0.80612293]
 [ 0.50564147  0.44107239  0.15614676  0.04891502]]

Notice how both the dims and shape change according to the input data.  Although dims and shape appear to have the same function, the difference will become quite clear in the section on tensor products and partial traces.

<div class="info">
**Hint**: If you are running QuTiP from a python script you must use the `print` function to view the Qobj attributes.
</div>

##States and Operators

Manually specifying the data for each quantum object is inefficient. Even more so when most objects correspond to commonly used types such as the ladder operators of a harmonic oscillator, the Pauli spin operators for a two-level system, or state vectors such as Fock states. Therefore, QuTiP includes predefined objects for a variety of states:

<table>
  <tr>
    <th>States</th>
    <th>Command (# = optional)</th>
    <th>Inputs</th>
  </tr>
  <tr>
    <td>Fock State</td>
    <td>`basis(N, #m)` or `fock(N, #m)`</td>
    <td>N = # of levels in Hilbert space, m = level containing excitation (0 if m not given).</td>
  </tr>
  <tr>
    <td>Fock State Density Matrix</td>
    <td>`fock_dm(N, #m)`</td>
    <td>Same as above.</td>
  </tr>
  <tr>
    <td>Coherent State</td>
    <td>`coherent(N, alpha)`</td>
    <td>alpha = complex number (eigenvalue) defining coherent state.</td>
  </tr>
  <tr>
    <td>Coherent State Density Matrix</td>
    <td>`coherent_dm(N, alpha)`</td>
    <td>Same as above.</td>
  </tr>
  <tr>
    <td>Thermal State Density Matrix</td>
    <td>`thermal_dm(N, n)`</td>
    <td>n = particle number expectation value.</td>
  </tr>
</table>

and operators:

<table>
  <tr>
    <th>Operator</th>
    <th>Command (# = optional)</th>
    <th>Inputs</th>
  </tr>
  <tr>
    <td>Identity</td>
    <td>`qeye(N)` or `identity(N)`</td>
    <td>N = # of levels in Hilbert space.</td>
  </tr>
  <tr>
    <td>Lowering (destruction) Operator</td>
    <td>`destroy(N)`</td>
    <td></td>
  </tr>
  <tr>
    <td>Raising (creation) Operator</td>
    <td>`create(N)`</td>
    <td></td>
  </tr>
  <tr>
    <td>Number Operator</td>
    <td>`num(N)`</td>
    <td></td>
  </tr>
  <tr>
    <td>Single-Mode Displacement Operator</td>
    <td>`displace(N, alpha)`</td>
    <td>alpha = Complex displacement amplitude.</td>
  </tr>
  <tr>
    <td>Single-Mode Squeezing Operator</td>
    <td>`squeeze(N, sp)`</td>
    <td>sp = Squeezing parameter.</td>
  </tr>
  <tr>
    <td>Pauli Pauli X-Operator (sigma-x)</td>
    <td>`sigmax()`</td>
    <td></td>
  </tr>
  <tr>
    <td>Pauli Spin Y-Operator (sigma-y)</td>
    <td>`sigmay()`</td>
    <td></td>
  </tr>
  <tr>
    <td>Pauli Spin Z-Operator (sigma-z)</td>
    <td>`sigmaz()`</td>
    <td></td>
  </tr>
  <tr>
    <td>Spin Raising Operator (sigma-plus)</td>
    <td>`sigmap()`</td>
    <td></td>
  </tr>
  <tr>
    <td>Spin Lowering Operator (sigma-minus)</td>
    <td>`sigmam()`</td>
    <td><br></td>
  </tr>
  <tr>
    <td>Higher-Spin Operators</td>
    <td>`jmat(j, #s)`</td>
    <td>j = int or half-int representing spin. s= 'x', 'y', 'z', '+', or '-'.</td>
  </tr>
</table>


As an example, we give the output for a few of these functions:

In [24]:
basis(5,3)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]

In [25]:
coherent(5,0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.77880170+0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.00000000-0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [26]:
 destroy(4)

Quantum object: dims = [[4], [4]], shape = [4, 4], type = oper, isherm = False
Qobj data =
[[ 0.          1.          0.          0.        ]
 [ 0.          0.          1.41421356  0.        ]
 [ 0.          0.          0.          1.73205081]
 [ 0.          0.          0.          0.        ]]

In [27]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [28]:
jmat(5/2.0,'+')

Quantum object: dims = [[6], [6]], shape = [6, 6], type = oper, isherm = False
Qobj data =
[[ 0.          2.23606798  0.          0.          0.          0.        ]
 [ 0.          0.          2.82842712  0.          0.          0.        ]
 [ 0.          0.          0.          3.          0.          0.        ]
 [ 0.          0.          0.          0.          2.82842712  0.        ]
 [ 0.          0.          0.          0.          0.          2.23606798]
 [ 0.          0.          0.          0.          0.          0.        ]]

###Qobj Attributes

We have seen that a quantum object has several internal attributes, such as data, dims, and shape.  These can be accessed in the following way:

In [30]:
q = destroy(4)
q.dims

[[4], [4]]

In [31]:
q.shape 

[4, 4]

In general, the attributes (properties) of a `Qobj` object (or any Python class) can be retrieved using the `Q.attribute` notation.  In addition to the attributes shown with the `print` function, the `Qobj` class also has the following:

<table>
  <tr>
    <th>Property</th>
    <th>Attribute</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Data</td>
    <td>Q.data</td>
    <td>Sparse matrix representing quantum state or operator.</td>
  </tr>
  <tr>
    <td>Dimensions</td>
    <td>Q.dims</td>
    <td>List keeping track of shapes for individual components of a multipartite system (for tensor products and partial traces).</td>
  </tr>
  <tr>
    <td>Shape</td>
    <td>Q.shape</td>
    <td>Dimensions of underlying data matrix.</td>
  </tr>
  <tr>
    <td>is Hermitian?</td>
    <td>Q.isherm</td>
    <td>Is operator Hermitian or not?</td>
  </tr>
  <tr>
    <td>Type</td>
    <td>Q.type</td>
    <td></td>
  </tr>
</table>

<center>
<img src='images/basicoperations/quide-basics-qobj-box.png'>
<p>The `Qobj` class viwed as a container for the properties needed to characterize a quantum operator or state vector.</p>
</center>

For the destruction operator above:

In [32]:
q.type

'oper'

In [33]:
q.isherm

False

In [34]:
 q.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

The data attribute returns a message stating that the data is a sparse matrix. All `Qobj` instances store their data as a sparse matrix to save memory. To access the underlying dense matrix one needs to use the `Q.full()` function as described below.

###Qobj Math

The rules for mathematical operations on ``Qobj`` instances are similar to standard matrix arithmetic:

In [36]:
q = destroy(4)
x = sigmax()
q + 5

Quantum object: dims = [[4], [4]], shape = [4, 4], type = oper, isherm = False
Qobj data =
[[ 5.          1.          0.          0.        ]
 [ 0.          5.          1.41421356  0.        ]
 [ 0.          0.          5.          1.73205081]
 [ 0.          0.          0.          5.        ]]

In [37]:
x * x

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0.  1.]]

In [38]:
q ** 3 

Quantum object: dims = [[4], [4]], shape = [4, 4], type = oper, isherm = False
Qobj data =
[[ 0.          0.          0.          2.44948974]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]

In [39]:
x / np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = [2, 2], type = oper, isherm = True
Qobj data =
[[ 0.          0.70710678]
 [ 0.70710678  0.        ]]

Of course, like matrices, multiplying two objects of incompatible shape throws an error:

In [40]:
q * x

TypeError: Incompatible Qobj shapes

In addition, the logic operators is equal `==` and is not equal `!=` are also supported.

<a id='functions'></a>

##Functions Acting on the Qobj Class

Like attributes, the quantum object class has defined functions (methods) that operate on ``Qobj`` class instances. For a general quantum object ``Q``:

<table>
  <tr>
    <th>Function</th>
    <th>Command</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Hermicity Check</td>
    <td>`Q.check_herm()`</td>
    <td>Check if Qobj is Hermitian.</td>
  </tr>
  <tr>
    <td>Conjugate</td>
    <td>`Q.conj()`</td>
    <td>Conjugate of Qobj.</td>
  </tr>
  <tr>
    <td>Dagger (adjoint)</td>
    <td>`Q.dag()`</td>
    <td>Adjoint of Qobj.</td>
  </tr>
  <tr>
    <td>Diagonal</td>
    <td>`Q.diag()`</td>
    <td>Returns array of diagonal elements.</td>
  </tr>
  <tr>
    <td>Eigenenergies</td>
    <td>`Q.eigenenergies()`</td>
    <td>Eigenenergies (values) of a Qobj.</td>
  </tr>
  <tr>
    <td>Eliminate States</td>
    <td>`Q.eliminate_states(inds)`</td>
    <td>Qobj with states is list 'inds' removed.</td>
  </tr>
  <tr>
    <td>Exponential</td>
    <td>`Q.expm()`</td>
    <td>Matrix exponential of Qobj.</td>
  </tr>
  <tr>
    <td>Extract States</td>
    <td>`Q.extract_states(inds)`</td>
    <td>Qobj with only states listed in 'inds'.</td>
  </tr>
  <tr>
    <td>Full</td>
    <td>`Q.full()`</td>
    <td>Returns full (dense) array of Qobj data.</td>
  </tr>
  <tr>
    <td>Groundstate</td>
    <td>`Q.groundstate()`</td>
    <td>Eigenvalue &amp; vector of Qobj ground state.</td>
  </tr>
  <tr>
    <td>Matrix Element</td>
    <td>`Q.matrix_element(bra,ket)`</td>
    <td>Matrix element &lt;bra|Q|ket&gt;.</td>
  </tr>
  <tr>
    <td>Norm</td>
    <td>`Q.norm()`</td>
    <td>Returns L2-norm for states and trace norm for operators.</td>
  </tr>
  <tr>
    <td>Overlap</td>
    <td>`Q.overlap(state)`</td>
    <td>Overlap between Qobj and a given state.</td>
  </tr>
  <tr>
    <td>Partial Trace</td>
    <td>`Q.ptrace(sel)`</td>
    <td>Partial trace returning components selected using 'sel'.</td>
  </tr>
  <tr>
    <td>Permute</td>
    <td>`Q.permute(order)`</td>
    <td>Permutes tensor structure of Qobj in a given order.</td>
  </tr>
  <tr>
    <td>Sqrt</td>
    <td>`Q.sqrt()`</td>
    <td>Matrix sqrt of Qobj,</td>
  </tr>
  <tr>
    <td>Tidyup</td>
    <td>`Q.tidyup()`</td>
    <td>Removes small elements from Qobj.</td>
  </tr>
  <tr>
    <td>Trace</td>
    <td>`Q.trace()`</td>
    <td>Trace of Qobj.</td>
  </tr>
  <tr>
    <td>Transform</td>
    <td>`Q.transform(inpt)`</td>
    <td>Basis transformation defined by matrix or list of kets given by 'inpt'.</td>
  </tr>
  <tr>
    <td>Transpose</td>
    <td>`Q.transpose()`</td>
    <td>Transpose of Qobj.</td>
  </tr>
  <tr>
    <td>Unit</td>
    <td>`Q.unit()`</td>
    <td>Returns normalized Qobj.</td>
  </tr>
</table>

In [41]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = [5, 1], type = ket
Qobj data =
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]

In [42]:
basis(5, 3).dag()

Quantum object: dims = [[1], [5]], shape = [1, 5], type = bra
Qobj data =
[[ 0.  0.  0.  1.  0.]]

In [43]:
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = [5, 5], type = oper, isherm = True
Qobj data =
[[ 0.36791117  0.36774407  0.26105441  0.14620658  0.08826704]
 [ 0.36774407  0.36757705  0.26093584  0.14614018  0.08822695]
 [ 0.26105441  0.26093584  0.18523331  0.10374209  0.06263061]
 [ 0.14620658  0.14614018  0.10374209  0.05810197  0.035077  ]
 [ 0.08826704  0.08822695  0.06263061  0.035077    0.0211765 ]]

In [44]:
coherent_dm(5, 1).diag()

array([ 0.36791117,  0.36757705,  0.18523331,  0.05810197,  0.0211765 ])

In [45]:
coherent_dm(5, 1).full()

array([[ 0.36791117+0.j,  0.36774407+0.j,  0.26105441+0.j,  0.14620658+0.j,
         0.08826704+0.j],
       [ 0.36774407+0.j,  0.36757705+0.j,  0.26093584+0.j,  0.14614018+0.j,
         0.08822695+0.j],
       [ 0.26105441+0.j,  0.26093584+0.j,  0.18523331+0.j,  0.10374209+0.j,
         0.06263061+0.j],
       [ 0.14620658+0.j,  0.14614018+0.j,  0.10374209+0.j,  0.05810197+0.j,
         0.03507700+0.j],
       [ 0.08826704+0.j,  0.08822695+0.j,  0.06263061+0.j,  0.03507700+0.j,
         0.02117650+0.j]])

In [46]:
 coherent_dm(5, 1).norm()

1.0

In [47]:
coherent_dm(5, 1).sqrtm()

Quantum object: dims = [[5], [5]], shape = [5, 5], type = oper, isherm = True
Qobj data =
[[ 0.36791118  0.36774407  0.26105441  0.14620658  0.08826704]
 [ 0.36774407  0.36757705  0.26093584  0.14614018  0.08822695]
 [ 0.26105441  0.26093584  0.18523331  0.10374209  0.06263061]
 [ 0.14620658  0.14614018  0.10374209  0.05810197  0.035077  ]
 [ 0.08826704  0.08822695  0.06263061  0.035077    0.0211765 ]]

In [48]:
coherent_dm(5, 1).tr()

1.0

In [49]:
(basis(4, 2) + basis(4, 1)).unit()

Quantum object: dims = [[4], [1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [ 0.70710678]
 [ 0.        ]]

In [1]:
from IPython.core.display import HTML
def css_styling():
    styles = open("../styles/guide.css", "r").read()
    return HTML(styles)
css_styling()